"""
Export the per-battery B5/B6/B7 datasets into web/js/data.js as plain JS
objects so the app works without any server or fetch/CORS setup.

Run (from repo root):
    py web/scripts/export_data.py
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SPLITS = os.path.join(ROOT, "battery_splits")
OUT = os.path.join(ROOT, "web", "js", "data.js")

COLUMNS = [
    "cycle", "chI", "chV", "chT",
    "disI", "disV", "disT", "BCt", "SOH", "RUL",
]

data = {}
for name in ["B5", "B6", "B7"]:
    path = os.path.join(SPLITS, f"{name}.csv")
    cols = {c: [] for c in COLUMNS}
    with open(path) as f:
        for row in csv.DictReader(f):
            for c in COLUMNS:
                cols[c].append(float(row[c]))
    data[name] = cols

js = "/* Auto-generated by web/scripts/export_data.py - do not edit */\n"
js += "window.BATTERY_DATA = "
js += json.dumps(data, separators=(",", ":"))
js += ";\n"

with open(OUT, "w") as f:
    f.write(js)

for name in ["B5", "B6", "B7"]:
    print(f"{name}: {len(data[name]['cycle'])} cycles")

print(f"Wrote {OUT} ({os.path.getsize(OUT)} bytes)")
