"""
Export the trained Random Forest model to a browser-friendly model.js
(embedded as a <script>) so the frontend can run predictions purely in
JavaScript - no backend, no fetch(), works even over file://.

Run (from repo root):
    py web/scripts/export_model.py
"""
import json
import os
import pickle

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(ROOT, "outputs", "battery_rul_rf_model.pkl")
OUT = os.path.join(ROOT, "web", "js", "model.js")

pkg = pickle.load(open(SRC, "rb"))
rf = pkg["model"]
features = pkg["features"]
meta = pkg["metadata"]

trees = []
for est in rf.estimators_:
    t = est.tree_
    value = t.value[:, 0, 0]  # leaf means
    trees.append({
        "left": t.children_left.tolist(),
        "right": t.children_right.tolist(),
        "feature": t.feature.tolist(),
        "threshold": [round(float(x), 6) for x in t.threshold],
        "value": [round(float(v), 6) for v in value],
    })

model = {
    "features": features,
    "nTrees": rf.n_estimators,
    "metadata": {
        "model_type": meta["model_type"],
        "n_estimators": int(meta["n_estimators"]),
        "max_depth": int(meta["max_depth"]),
        "avg_r2_lobo": round(float(meta["avg_r2_lobo"]), 4),
        "avg_mae_lobo": round(float(meta["avg_mae_lobo"]), 2),
        "avg_rmse_lobo": round(float(meta["avg_rmse_lobo"]), 2),
        "best_battery": meta["best_battery"],
        "trained_on": meta["trained_on"],
    },
    "trees": trees,
}

js = "/* Auto-generated by web/scripts/export_model.py - do not edit */\n"
js += "window.RUL_MODEL = "
js += json.dumps(model, separators=(",", ":"))
js += ";\n"

with open(OUT, "w") as f:
    f.write(js)

print(f"Exported {len(trees)} trees -> {OUT} ({os.path.getsize(OUT) / 1e6:.2f} MB)")
print(f"Features: {features}")
print(f"Metadata: {model['metadata']}")
